@module = attraction

POST {{baseUrl}}/{{module}}/create HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "name": "Wyspa słodowa",
    "address": {
        "city": "Wrocław",
        "zipCode": "50-200"
    }
}

###

POST {{baseUrl}}/{{module}}/edit/62191ba488d1019ce057bed1 HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "description": "asd"
}

###

POST {{baseUrl}}/{{module}}/delete/62191fb683e84adabb3b54af HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/{{module}}/all HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/{{module}}/get/62191fb683e84adabb3b54af HTTP/1.1
Authorization: {{auth}}
