@hostname = localhost
@port = 9000
@suffix = api
@module = group
@baseUrl = http://{{hostname}}:{{port}}/{{suffix}}/{{module}}
@contentType = application/json
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTkwMTUzZWVjNzQ4ODA3NmQzNjg2MiIsImlhdCI6MTY0NTgzMjMzNSwiZXhwIjozMjkyMDI0NjcwLCJpc3MiOiJ0cmF2ZWxyLWlzc3VlciJ9.d6LP-H2MqwBeWGvQfRZDNL_aLft1dJfm0eGUPaxrYh8

GET {{baseUrl}}/62190219b103f1dde78b1d2d HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/all HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/get-user-groups/6219028eb103f1dde78b1d33 HTTP/1.1
Authorization: {{auth}}

###

POST {{baseUrl}}/edit/6219682a543fae5ad6e8b8fb HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "name": "Grupa 555"
}

###

POST {{baseUrl}}/delete/6219682a543fae5ad6e8b8fb HTTP/1.1
Authorization: {{auth}}

###

POST {{baseUrl}}/create HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "name": "Grupa 234"
}

###

POST {{baseUrl}}/join HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "groupId": "62190219b103f1dde78b1d2d",
    "memberId": "6219059129b0a8bf87a6ea42",
    "invitationCode": "123ABC"
}

###

POST {{baseUrl}}/add HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "groupId": "6219682a543fae5ad6e8b8fb",
    "memberEmail": "user4@travelr.com"
}

###

POST {{baseUrl}}/remove HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "groupId": "6219682a543fae5ad6e8b8fb",
    "memberId": "6219682a543fae5ad6e8b8fb"
}
