@module = group

GET {{baseUrl}}/{{module}}/62190219b103f1dde78b1d2d HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/{{module}}/all HTTP/1.1
Authorization: {{auth}}

###
GET {{baseUrl}}/{{module}}/get-user-groups/6219028eb103f1dde78b1d33 HTTP/1.1
Authorization: {{auth}}

###

POST {{baseUrl}}/{{module}}/edit/6219682a543fae5ad6e8b8fb HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "name": "Grupa 555"
}

###

POST {{baseUrl}}/{{module}}/delete/6219682a543fae5ad6e8b8fb HTTP/1.1
Authorization: {{auth}}

###

POST {{baseUrl}}/{{module}}/create HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "name": "Grupa Rozpierdolu!"
}

###

POST {{baseUrl}}/{{module}}/join HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "groupId": "621a2396621a9872bba76870",
    "memberId": "621a2372621a9872bba7686b",
    "invitationCode": "123ABC"
}

###

POST {{baseUrl}}/{{module}}/add HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "groupId": "621a2396621a9872bba76870",
    "memberEmail": "user3@travelr.com"
}

###

POST {{baseUrl}}/{{module}}/remove HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "groupId": "6219682a543fae5ad6e8b8fb",
    "memberId": "6219682a543fae5ad6e8b8fb"
}
