@module = journey

GET {{baseUrl}}/{{module}}/all HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/{{module}}/get/62192a6b1504664474863299 HTTP/1.1
Authorization: {{auth}}

###

POST {{baseUrl}}/{{module}}/create HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "groupId": "621a2396621a9872bba76870",
    "data": {
        "name": "Wycieczka po Wrocławiu",
        "description": "Spacerek po miejscach",
        "startDate": "2022-02-28",
        "endDate": "2022-02-28",
        "attractions": [
            "621a2403621a9872bba76886",
            "621a2441621a9872bba76889",
            "621a2450621a9872bba7688c"
        ]
    }
}

###

POST {{baseUrl}}/{{module}}/edit/621a24b4621a9872bba76891 HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "name": "Twoja stara"
}

###

POST {{baseUrl}}/{{module}}/delete/62192a6b1504664474863299 HTTP/1.1
Authorization: {{auth}}
