@module = journey

GET {{baseUrl}}/{{module}}/all HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/{{module}}/get/62192a6b1504664474863299 HTTP/1.1
Authorization: {{auth}}

###

POST {{baseUrl}}/{{module}}/create HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "groupId": "621bc1dd80bea7cf1485c29f",
    "data": {
        "name": "Wycieczka po Wrocławiu",
        "description": "Spacerek po miejscach",
        "startDate": "2022-03-03",
        "endDate": "2022-03-03",
        "attractions": [
            "621bc28c80bea7cf1485c2b0",
            "621bc29880bea7cf1485c2b3"
        ]
    }
}

###

POST {{baseUrl}}/{{module}}/edit/621a24b4621a9872bba76891 HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}

{
    "name": "Twoja stara"
}

###

POST {{baseUrl}}/{{module}}/delete/62192a6b1504664474863299 HTTP/1.1
Authorization: {{auth}}
