@hostname = localhost
@port = 9000
@suffix = api
@module = user
@baseUrl = http://{{hostname}}:{{port}}/{{suffix}}/{{module}}
@contentType = application/json
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTkwMjhlYjEwM2YxZGRlNzhiMWQzMyIsImlhdCI6MTY0NTgzMTcyNSwiZXhwIjozMjkyMDIzNDUwLCJpc3MiOiJ0cmF2ZWxyLWlzc3VlciJ9.zn8P--w0bgjqQ8CdqwobaMj0Bk6Qj73UtzetVsuBZCA

GET {{baseUrl}}/get/6212bbb8c9881ffe00efc155 HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/all HTTP/1.1
Authorization: {{auth}}

###

GET {{baseUrl}}/check/username/user6 HTTP/1.1

###

POST {{baseUrl}}/register HTTP/1.1
content-type: {{contentType}}

{
    "username": "user5",
    "email": "user5@travelr.com",
    "password": "user5",
    "firstName": "Michael",
    "lastName": "Dawson",
    "birthdate": "2000-06-27"
}

###

POST {{baseUrl}}/login HTTP/1.1
content-type: {{contentType}}

{
    "username": "user4",
    "password": "user4"
}

###
POST {{baseUrl}}/edit/6212bbf3c9881ffe00efc160 HTTP/1.1
content-type: {{contentType}}
Authorization: {{auth}}


{
    "firstName": "Amadeusz",
    "lastName": "Pawle",
    "birthdate": "1998-08-10"
}

###

POST {{baseUrl}}/delete/6212bbf3c9881ffe00efc160 HTTP/1.1
Authorization: {{auth}}
